# Generated by Django 4.1.1 on 2022-09-15 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
