# Generated by Django 4.1.1 on 2022-09-15 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="User", new_name="DatosUsuarios",),
    ]
