# Generated by Django 4.1.1 on 2022-09-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_rename_user_datosusuarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="datosusuarios",
            name="apellido",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datosusuarios",
            name="contraseña",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datosusuarios",
            name="correo",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datosusuarios",
            name="telefono",
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name="datosusuarios",
            name="usuario",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
