# Generated by Django 4.1.1 on 2022-09-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_datosusuarios_apellido_datosusuarios_contraseña_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datosusuarios",
            name="usuario",
            field=models.CharField(default="nombre", max_length=30),
        ),
    ]
