# Generated by Django 4.1.1 on 2022-09-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0008_alter_datosusuarios_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatosLibros",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.TextField(max_length=60)),
                ("autor", models.CharField(max_length=60)),
                ("editorial", models.CharField(max_length=60)),
                ("categoria", models.CharField(max_length=60)),
                ("estado", models.CharField(max_length=60)),
                ("cantidad", models.IntegerField(default=0)),
                ("intencion", models.CharField(max_length=60)),
                ("precio", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="datosusuarios",
            name="contraseña",
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name="datosusuarios",
            name="correo",
            field=models.EmailField(max_length=100),
        ),
    ]
