# Generated by Django 4.1.1 on 2022-09-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0009_datoslibros_alter_datosusuarios_contraseña_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datoslibros",
            name="usuarioID",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="login.datosusuarios",
            ),
            preserve_default=False,
        ),
    ]
