# Generated by Django 4.1.1 on 2022-09-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0010_datoslibros_usuarioid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="datoslibros", old_name="usuarioID", new_name="usuario",
        ),
    ]
