# Generated by Django 4.1.1 on 2022-09-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0011_rename_usuarioid_datoslibros_usuario"),
    ]

    operations = [
        migrations.RemoveField(model_name="datoslibros", name="cantidad",),
    ]
