# Generated by Django 4.1.1 on 2022-09-19 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0012_remove_datoslibros_cantidad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datosusuarios",
            name="contraseña",
            field=models.CharField(max_length=50),
        ),
    ]
