# Generated by Django 4.1.1 on 2022-09-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0013_alter_datosusuarios_contraseña"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datosusuarios", name="telefono", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="datosusuarios",
            name="usuario",
            field=models.CharField(max_length=30),
        ),
    ]
