# Generated by Django 4.1.1 on 2022-09-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0014_alter_datosusuarios_telefono_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datosusuarios",
            name="telefono",
            field=models.CharField(max_length=10),
        ),
    ]
