# Generated by Django 4.1.1 on 2022-09-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="libro_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
