# Generated by Django 4.1.1 on 2022-09-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_books_libro_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=100)),
            ],
        ),
    ]
