# Generated by Django 4.1.1 on 2022-09-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_libro"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="categoria",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="books",
            name="estado",
            field=models.IntegerField(choices=[], default=0),
        ),
    ]
