# Generated by Django 4.1.1 on 2022-09-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_alter_books_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="estado",
            field=models.CharField(
                choices=[("1", "Excelente"), ("2", "Bueno"), ("3", "Regular")],
                max_length=1,
            ),
        ),
    ]
