# Generated by Django 4.1.1 on 2022-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_books_estado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="estado",
            field=models.CharField(
                choices=[
                    ("Excelente", "Excelente"),
                    ("Bueno", "Bueno"),
                    ("Regular", "Regular"),
                ],
                max_length=15,
            ),
        ),
    ]
