# Generated by Django 4.1.1 on 2022-09-24 23:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_books_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="pais",
            field=django_countries.fields.CountryField(default="", max_length=2),
        ),
    ]
