# Generated by Django 4.1.1 on 2022-09-24 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_books_pais"),
    ]

    operations = [
        migrations.RemoveField(model_name="books", name="pais",),
    ]
