# Generated by Django 4.1.1 on 2022-09-25 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_remove_books_pais"),
    ]

    operations = [
        migrations.DeleteModel(name="Libro",),
    ]
