# Generated by Django 4.1.1 on 2022-09-25 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_delete_libro"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="fecha",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
