# Generated by Django 4.1.1 on 2022-09-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0011_books_fecha"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("Cientifico", "Cientifico"),
                    ("Literatura", "Literatura"),
                    ("Biografia", "Biografia"),
                    ("Libro de texto", "Libro de texto"),
                    ("Monografia", "Monografia"),
                    ("Poeticos", "Poeticos"),
                    ("Juveniles", "Juveniles"),
                    ("Ficcion", "Ficcion"),
                    ("Comedia", "Comedia"),
                    ("Leyenda", "Leyenda"),
                    ("Epopeya", "Epopeya"),
                    ("Fabula", "Fabula"),
                ],
                max_length=200,
            ),
        ),
    ]
