# Generated by Django 4.1.1 on 2022-09-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0012_alter_books_categoria"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=250)),
            ],
        ),
    ]
