# Generated by Django 4.1.1 on 2022-09-27 18:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0014_alter_books_categoria_alter_books_estado"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="likes",
            field=models.ManyToManyField(
                related_name="book_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
