# Generated by Django 4.1.1 on 2022-09-27 20:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0015_books_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="reseña",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
